'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("B4X_WrapperHelper.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 package B4AWrapperClass;
        '''
        '''import anywheresoftware.b4a.AbsObjectWrapper;
        '''import anywheresoftware.b4a.BA;
        '''import anywheresoftware.b4a.BA.Hide;
        '''import anywheresoftware.b4a.BA.ShortName;
        '''import anywheresoftware.b4a.BA.Version;
        '''import anywheresoftware.b4a.BALayout;
        '''import anywheresoftware.b4a.BA.DependsOn;
        '''import anywheresoftware.b4a.BA.ActivityObject;
        '''import anywheresoftware.b4a.IOnActivityResult;
        '''import anywheresoftware.b4a.BA.Permissions;
        '''
        '''import android.content.Intent;
        '''import android.content.Co [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property AbsObjectWrapper() As String
            Get
                Return ResourceManager.GetString("AbsObjectWrapper", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 package B4AWrapperClass;
        '''
        '''
        '''import anywheresoftware.b4a.AbsObjectWrapper;
        '''import anywheresoftware.b4a.BA;
        '''import anywheresoftware.b4a.objects.collections.List;
        '''import anywheresoftware.b4a.BA.Hide;
        '''import anywheresoftware.b4a.BA.ShortName;
        '''import anywheresoftware.b4a.BA.Version;
        '''import anywheresoftware.b4a.BA.ActivityObject;
        '''import anywheresoftware.b4a.IOnActivityResult;
        '''import anywheresoftware.b4a.BA.Permissions;
        '''import anywheresoftware.b4a.keywords.Bit;
        '''import anywheresoftware.b4a.objects.Inten [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property FunctionWrapper() As String
            Get
                Return ResourceManager.GetString("FunctionWrapper", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 public void startFunction() {
        '''        ion = new IOnActivityResult() {
        '''            @Override
        '''            public void ResultArrived(int resultCode, Intent data) {
        '''                BA.Log(&quot;ResultArrived&quot;);
        '''                if (resultCode == Activity.RESULT_OK) {
        '''                    BA.Log(&quot;RESULT_OK&quot;);
        '''                    //...
        '''                }
        '''                ba.raiseEvent(B4AWrapperClass.this, eventName + &quot;_result&quot;, true, intent);
        '''            }
        '''        };
        '''        ba.startActivityForResult(ion, new [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property onActivityResultTip() As String
            Get
                Return ResourceManager.GetString("onActivityResultTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 package ViewNameWrapper;
        '''
        '''
        '''import anywheresoftware.b4a.AbsObjectWrapper;
        '''import anywheresoftware.b4a.BA;
        '''import anywheresoftware.b4a.BA.ActivityObject;
        '''import anywheresoftware.b4a.BA.DesignerProperties;
        '''import anywheresoftware.b4a.BA.Events;
        '''import anywheresoftware.b4a.BA.Hide;
        '''import anywheresoftware.b4a.BA.Property;
        '''import anywheresoftware.b4a.BA.RaisesSynchronousEvents;
        '''import anywheresoftware.b4a.BA.ShortName;
        '''import anywheresoftware.b4a.BA.Version;
        '''import anywheresoftware.b4a.keywords.Comm [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ViewWrapper1() As String
            Get
                Return ResourceManager.GetString("ViewWrapper1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 package ViewNameWrapper;
        '''
        '''import anywheresoftware.b4a.AbsObjectWrapper;
        '''import anywheresoftware.b4a.BA;
        '''import anywheresoftware.b4a.BA.ActivityObject;
        '''import anywheresoftware.b4a.BA.DesignerProperties;
        '''import anywheresoftware.b4a.BA.Events;
        '''import anywheresoftware.b4a.BA.Hide;
        '''import anywheresoftware.b4a.BA.Property;
        '''import anywheresoftware.b4a.BA.RaisesSynchronousEvents;
        '''import anywheresoftware.b4a.BA.ShortName;
        '''import anywheresoftware.b4a.BA.Version;
        '''import anywheresoftware.b4a.BALayout;
        '''impo [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ViewWrapper2() As String
            Get
                Return ResourceManager.GetString("ViewWrapper2", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
